-- 笼罩相机
local config = {

    path = 'Timeline/Copy/plot3/plot3-2wave3end.prefab',
    assetPath = 'Timeline/Copy/plot3/plot3-2wave3end.playable',
	plotLanguage = 'SectionLanguage3',
    track_list = {
        {
		    name = 'Cinemachine Track',
            bindingType = 3,
            bindingPath = false,
            bindingWujiangCamp = false,
            bindingWujiangID = false,
            clipingType = 2,
            clip_list = {},
		},
		{	
		    name = 'Animation Track',
			bindingType = 4,
            bindingPath = '6666',
            bindingWujiangCamp = false,
			bindingWujiangID = false,
            clip_list = {},
		},
		{
            name = 'Animation Track (1)',
			bindingType = 4,
            bindingPath = '1042',
            bindingWujiangCamp = false,
			bindingWujiangID = false,
            clip_list = {},
		},
		{
            name = 'Animation Track (2)',
			bindingType = 4,
            bindingPath = '1001',
            bindingWujiangCamp = false,
			bindingWujiangID = false,
            clip_list = {},
		},
		{
		    name = 'Animation Track (3)',
			bindingType = 4,
            bindingPath = '1002',
            bindingWujiangCamp = false,
			bindingWujiangID = false,
            clip_list = {},
		},
		{
		    name = 'Animation Track (4)',
			bindingType = 4,
            bindingPath = '1003',
            bindingWujiangCamp = false,
			bindingWujiangID = false,
            clip_list = {},
		},
		{
		    name = 'Custom Anim Track',
			bindingType = 4,
            bindingPath = '6666',
            bindingWujiangCamp = false,
			bindingWujiangID = false,
            clip_list = {},
		},
	},
	load_list = {
        {
            path = "Models/6666/6666_showoff.prefab",
            createInstance = true,
            name = "6666",
            instancePos = {0, 0, 0},
            instanceRotation = {0, 0, 0},
        },
		{
            path = "Models/1042/1042_3.prefab",
            createInstance = true,
            name = "1042",
            instancePos = {0, 0, 0},
            instanceRotation = {0, 0, 0},
        },
		{
		    path = "Models/1001/1001_3.prefab",
            createInstance = true,
            name = "1001",
            instancePos = {0, 0, 0},
            instanceRotation = {0, 0, 0},
		},
		{
		    path = "Models/1002/1002_3.prefab",
            createInstance = true,
            name = "1002",
            instancePos = {0, 0, 0},
            instanceRotation = {0, 0, 0},
		},
		{
		    path = "Models/1003/1003_3.prefab",
            createInstance = true,
            name = "1003",
            instancePos = {0, 0, 0},
            instanceRotation = {0, 0, 0},
		},
    },
}

return config
