NetEnum = {
    LOGIN_STATUS_NONE = 0,
    LOGIN_STATUS_LOGINING = 1,
    LOGIN_STATUS_DONE =2,
    LOGIN_STATUS_FAIL =3,

    MSG_SEND_NONE = 0,
    MSG_SEND_SENDING = 1,
    MSG_SEND_RECEIVED = 2,
    MSG_SEND_WAIT_RECONNET = 3,
}