--[[
-- added by wsh @ 2017-11-30
-- UI消息定义，手动添加
-- 定义格式：模块名_ON_事件描述 = "驼峰式消息名"
-- 注意：
-- 1、这类型的消息只在UI模块中流通，View层只关注这里的消息，由Model层发送
-- 2、如果窗口足够简单，那每次数据变化时发送OnRefresh消息就可以了，View层进行整体刷新，以避免消息臃肿
--]]

local UIMessageNames = {
	-- 框架消息
	UIFRAME_ON_WINDOW_CREATE = "UIFrameOnWindowCreeate",
	UIFRAME_ON_WINDOW_OPEN = "UIFrameOnWindowOpen",
	UIFRAME_ON_WINDOW_CLOSE = "UIFrameOnWindowClose",
	UIFRAME_ON_WINDOW_DESTROY = "UIFrameOnWindowDestroy",
	
	-- 模块消息添加到下面
	-- Login模块
	LOGIN_ON_SELECTED_SVR_CHG = "LoginOnSelectedSvrChg",
	LOGIN_ON_SERVER_LIST_CHG = "LoginOnServerListChg",
	-- UIPlot
	UIPLOT_ON_SKIP_BTN_SHOW = "UIPlotOnSkipBtnShow",
	UIPLOT_WUJIANG_ANIM = "UIPLOT_WUJIANG_ANIM",
	UIPLOT_WUJIANG_ROTATE = "UIPLOT_WUJIANG_ROTATE",
	UIPLOT_WUJIANG_OPEN = "UIPLOT_WUJIANG_OPEN",
	-- UIBattleFloat
	UIBATTLEFLOAT_SHOW_HP = "UIBattleFloatShowHp",
	UIBATTLEFLOAT_SHOW_NUQI = "UIBattleFloatShowNuqi",
	UIBATTLEFLOAT_SHOW_JUDGE = "UIBattleFloatShowJudge",
	UIBATTLEFLOAT_SHOW_ATTR = "UIBattleFloatShowAttr",	
	UIBATTLEFLOAT_SHOW_MASK = "UIBattleFloatShowMask",	
	UIBATTLEFLOAT_SHOW_INSCRIPANDHORSESKILL = "UIBattleFloatShowSkill", -- 目前仅用于命签与坐骑技能
	UIBATTLEFLOAT_SHOW_SKILL_MASK = "UIBattleFloatShowSkillMask",	
	UIBATTLEFLOAT_SHOW_ACTIVE_SKILL = "UIBATTLEFLOAT_SHOW_ACTIVE_SKILL",	
	UIBATTLEFLOAT_SHOW_HURT_END = "UIBATTLEFLOAT_SHOW_HURT_END", 
	-- Battle
	UIBATTLE_ACTOR_CREATE = "UIBattleActorCreate",
	UIBATTLE_ACTOR_DIE = "UIBattleActorDie",
	UIBATTLE_SHOW_BLOOD_BAR = "UIBattleShowBloodBar",
	UIBATTLE_HP_CHANGE = "UIBattleHPChange",
	UIBATTLE_START = "UIBattleStart",
	UIBATTLE_STOP = "UIBattleStop",
	UIBATTLE_WAVE_END = "UIBattleWaveEnd",
	UIBATTLE_ACTOR_BE_CONTROL = "UIBattleActorBeControl",
	UIBATTLE_SET_BATTLEARENAUI_ACTIVE = "UIBattleSetBattleArenaUIActive",
	UIBATTLE_SET_BATTLEARENAMIDDLEUI_ACTIVE = "UIBattleSetBattleArenaMiddleUIActive",
	UIBATTLE_ACTOR_GUIDE = "UIBattleActorGuide",
	UIBATTLE_ACTOR_INTERRUPT_GUIDE = "UIBattleActorInterruptGuide",
	UIBATTLE_PICK_BOX = "UIBattlePickBox",
	UIBATTLE_PICK_MONEY = "UIBattlePickMoney",
	UIBATTLE_PICK_GRAVE_BOX = "UIBattlePickGraveBox",
	UIBATTLE_SHENBING_CHOSEN = "UIBATTLE_SHENBING_CHOSEN",
	UIBATTLE_HIDE_MAINVIEW = "UIBATTLE_HIDE_MAINVIEW",
	UIBATTLE_SHOW_MAINVIEW = "UIBATTLE_SHOW_MAINVIEW",
	UIBATTLE_SHENBING_DIALOG_CLOSE = "UIBATTLE_SHENBING_DIALOG_CLOSE",
	UIBATTLE_GUILDWAR_FIGHT_NEWS = "UIBATTLE_GUILDWAR_FIGHT_NEWS",
	UIBATTLE_DRAGON_SKILL_PERFORM = "UIBATTLE_DRAGON_SKILL_PERFORM",
	MN_CLEAR_DRAGON_EFFECT = "MN_CLEAR_DRAGON_EFFECT",


	--武将界面
	MN_WUJIANG_SKILL_DETAIL_SHOW = "MN_WUJIANG_SKILL_DETAIL_SHOW",
	MN_WUJIANG_DEV_CARD_ITEM_SELECT = "MN_WUJIANG_DEV_CARD_ITEM_SELECT",
	MN_WUJIANG_DATA_CHG = "MN_WUJIANG_DATA_CHG",
	MN_WUJIANG_EXP_CHG = "MN_WUJIANG_EXP_CHG",
	MN_WUJIANG_INSCRIPTION_CHG = "MN_WUJIANG_INSCRIPTION_CHG",
	MN_WUJIANG_INSCRIPTION_BAG_SHOW = "MN_WUJIANG_INSCRIPTION_BAG_SHOW",
	MN_WUJIANG_INSCRIPTION_DETAIL_SHOW = "MN_WUJIANG_INSCRIPTION_DETAIL_SHOW",
	MN_WUJIANG_INSCRIPTION_ITEM_CLICK = "MN_WUJIANG_INSCRIPTION_ITEM_CLICK",
	MN_WUJIANG_MERGE_VIEW_SHOW = "MN_WUJIANG_MERGE_VIEW_SHOW",
	MN_WUJIANG_INSCRIPTION_CASE_LIST = "MN_WUJIANG_INSCRIPTION_CASE_LIST",
	MN_WUJIANG_INSCRIPTION_OPERATION = "MN_WUJIANG_INSCRIPTION_OPERATION",
	MN_WUJIANG_INSCRIPTION_CLICK_MASK = "MN_WUJIANG_INSCRIPTION_CLICK_MASK",
	MN_WUJIANG_RSP_INTIMACY_LIST = "MN_WUJIANG_RSP_INTIMACY_LIST",
	MN_WUJIANG_NTF_INTIMACY_CHG = "MN_WUJIANG_NTF_INTIMACY_CHG", 
	MN_WUJIANG_LOCK_CHG = "MN_WUJIANG_LOCK_CHG", 
	MN_WUJIANG_INSCRIPTION_MERGE = "MN_WUJIANG_INSCRIPTION_MERGE",
	MN_WUJIANG_INTIMACY_FLUSH = "MN_WUJIANG_INTIMACY_FLUSH", 
	MN_WUJIANG_POWER_CHG = "MN_WUJIANG_POWER_CHG",

	--军团界面
	MN_GUILD_BRIEF_LIST = "MN_GUILD_BRIEF_LIST",
	MN_GUILD_DONATION_UPDATE = "MN_GUILD_DONATION_UPDATE",
	MN_MYGUILD_BASEINFO_CHG = "MN_MYGUILD_BASEINFO_CHG",
	MN_GUILD_APPLY_LIST = "MN_GUILD_APPLY_LIST",
	MN_EXAMINE_GUILD = "MN_EXAMINE_GUILD",
	MN_GUILD_EXIT = "MN_GUILD_EXIT",
	MN_GUILD_RSP_GUILD_DETAIL = "MN_GUILD_RSP_GUILD_DETAIL",
	MN_GUILD_RSP_GUILD_TASK_LIST = "MN_GUILD_RSP_GUILD_TASK_LIST",
	MN_GUILD_RSP_COMPLETE_TASK = "MN_GUILD_RSP_COMPLETE_TASK",
	MN_GUILD_RSP_GUILD_DAILY = "MN_GUILD_RSP_GUILD_DAILY",
	MN_GUILD_RSP_SETTING = "MN_GUILD_RSP_SETTING",
	MN_GUILD_RSP_POST_RENAME = "MN_GUILD_RSP_POST_RENAME",
	MN_GUILD_RSP_GUILD_RANK_LIST = "MN_GUILD_RSP_GUILD_RANK_LIST",
	MN_GUILD_RSP_GUILD_SKILL_LIST = "MN_GUILD_RSP_GUILD_SKILL_LIST",
	MN_GUILD_RSP_FIND_GUILD = "MN_GUILD_RSP_FIND_GUILD",
	MN_GUILD_NTF_NOTIFY_BAR = "MN_GUILD_NTF_NOTIFY_BAR",
	MN_GUILD_RSP_SET_JOIN_TYPE = "MN_GUILD_RSP_SET_JOIN_TYPE",
	MN_GUILD_RSP_ALL_GUILD_BOSS_INFO = "MN_GUILD_RSP_ALL_GUILD_BOSS_INFO",
	MN_GUILD_RSP_TAKE_ALL_AWARD = "MN_GUILD_RSP_TAKE_ALL_AWARD",

	--群雄逐鹿
	MN_QUNXIONGZHULU_RSP_PANEL = "QUNXIONGZHULU_RSP_PANEL",
	MN_QUNXIONGZHULU_RSP_SEASON_RECORDS = "QUNXIONGZHULU_RSP_SEASON_RECORDS",
	MN_QUNXIONGZHULU_RSP_BATTLE_RECORD = "QUNXIONGZHULU_RSP_BATTLE_RECORD",
	MN_QUNXIONGZHULU_RSP_MATCH = "QUNXIONGZHULU_RSP_MATCH",
	MN_QUNXIONGZHULU_RSP_MATCH_CANCEL = "QUNXIONGZHULU_RSP_MATCH_CANCEL",
	MN_QUNXIONGZHULU_RSP_READY = "QUNXIONGZHULU_RSP_READY",
	MN_QUNXIONGZHULU_RSP_QUIT_BATTLE = "QUNXIONGZHULU_RSP_QUIT_BATTLE",
	MN_QUNXIONGZHULU_RSP_ARRANGE_BUZHEN = "QUNXIONGZHULU_RSP_ARRANGE_BUZHEN",	
	MN_QUNXIONGZHULU_NTF_RIVAL_BUZHEN_CHG = "MN_QUNXIONGZHULU_NTF_RIVAL_BUZHEN_CHG",
	MN_QUNXIONGZHULU_NTF_MATCH_RESULT = "MN_QUNXIONGZHULU_NTF_MATCH_RESULT",
	MN_QUNXIONGZHULU_NTF_MATCH_FAILED = "MN_QUNXIONGZHULU_NTF_MATCH_FAILED",
	MN_QUNXIONGZHULU_RSP_TAKE_SEASON_AWARD = "MN_QUNXIONGZHULU_RSP_TAKE_SEASON_AWARD",
	MN_QUNXIONGZHULU_NTF_PREPARE_DEADLINE = "MN_QUNXIONGZHULU_NTF_PREPARE_DEADLINE",

	--主界面
	MN_MAIN_TOP_STATE = "MN_MAIN_TOP_STATE",
	MN_RIGHT_MENU_STATE = "MN_RIGHT_MENU_STATE",
	MN_MAIN_TOP_RIGHT_CURRENCY_TYPE = "MN_MAIN_TOP_RIGHT_CURRENCY_TYPE",
	MN_MAIN_CHG_MIDDLE_CURRENCY_TYPE = "MN_MAIN_CHG_MIDDLE_CURRENCY_TYPE",
	MN_HIDE_MAIN = "MN_HIDE_MAIN",
	MN_SHOW_MAIN = "MN_SHOW_MAIN",
	MN_MAIN_ICON_REFRESH = "MN_MAIN_ICON_REFRESH",
	MN_MAIN_ICON_REFRESH_RED_POINT = "MN_MAIN_ICON_REFRESH_RED_POINT",
	MN_MAIN_FRIEND_TASK_RED_POINT = "MN_MAIN_FRIEND_TASK_RED_POINT",

	--福利界面
	MN_FULI_RSP_FULI_LIST = "MN_FULI_RSP_FULI_LIST",
	MN_FULI_RSP_GET_FULI_AWARD = "MN_FULI_RSP_GET_FULI_AWARD",
	MN_FULI_RSP_BUY_FUND = "MN_FULI_RSP_BUY_FUND",
	MN_FULI_NTF_FULI_CHG = "MN_FULI_NTF_FULI_CHG",
	MN_FULI_FUND_BUY_BTN_CLICK = "MN_FULI_FUND_BUY_BTN_CLICK",

	--活动界面
	MN_ACT_RSP_ACT_LIST = "MN_ACT_RSP_ACT_LIST",
	MN_ACT_RSP_TAKE_AWARD = "MN_ACT_RSP_TAKE_AWARD",
	MN_ACT_RSP_TURNTABLE_INTERFACE = "MN_ACT_RSP_TURNTABLE_INTERFACE",
	MN_ACT_RSP_TURNTABLE_LOTTERY = "MN_ACT_RSP_TURNTABLE_LOTTERY",
	MN_ACT_RSP_TAKE_TURNTABLE_BOX_AWARD = "MN_ACT_RSP_TAKE_TURNTABLE_BOX_AWARD",
	MN_RSP_DUOBAO_INTERFACE = "MN_RSP_DUOBAO_INTERFACE",
	MN_RSP_DUOBAO = "MN_RSP_DUOBAO",
	MN_ACT_RSP_GROUP_CHARGE_INTERFACE = "MN_ACT_RSP_GROUP_CHARGE_INTERFACE",
	MN_ACT_RSP_TAKE_GROUP_CHARGE_AWARD = "MN_ACT_RSP_TAKE_GROUP_CHARGE_AWARD",
	MN_ACT_RSP_JIXINGGAOZHAO_INTERFACE = "MN_ACT_RSP_JIXINGGAOZHAO_INTERFACE",
	MN_ACT_RSP_JIXINGGAOZHAO_LOTTERY = "MN_ACT_RSP_JIXINGGAOZHAO_LOTTERY",
	MN_ACT_RSP_REBATE_SHOP_INFO = "MN_ACT_RSP_REBATE_SHOP_INFO",
	MN_ACT_RSP_BUY_REBATE_SHOP_GOODS = "MN_ACT_RSP_BUY_REBATE_SHOP_GOODS",
	MN_ACT_RSP_GET_REBATE = "MN_ACT_RSP_GET_REBATE",

	--飘字
	MN_ADD_PROMPT = "MN_ADD_PROMPT",
	MN_CLEAR_MESSAGE = "MN_CLEAR_MESSAGE",
	MN_POWER_CHANGE = "MN_POWER_CHANGE",

	--布阵
	MN_LINEUP_ITEM_SELECT = "MN_LINEUP_ITEM_SELECT",
	MN_WUJIANG_SELECT = "MN_WUJIANG_SELECT",
	MN_LINEUP_APPLY_NEW = "MN_LINEUP_APPLY_NEW",
	MN_LINEUP_SELECT_EMPLOY_WUJIANG = "MN_LINEUP_SELECT_EMPLOY_WUJIANG",
	MN_LINEUP_CHECK_LINEUP_ILLEGAL = "MN_LINEUP_CHECK_LINEUP_ILLEGAL",
	MN_LINEUP_CLICK_DRAGON = "MN_LINEUP_CLICK_DRAGON",
	MN_LINEUP_REFRESH = "MN_LINEUP_REFRESH",

	--闯连营
	MN_CAMPSRUSH_INFO_CHG = "MN_CAMPSRUSH_INFO_CHG",
	MN_CAMPSRUSH_BUY_RESET_TIMES = "MN_CAMPSRUSH_BUY_RESET_TIMES",
	MN_CAMPS_RUSH_SWEEP_RESULT = "MN_CAMPS_RUSH_SWEEP_RESULT",
	MN_DEFEND_ROLE_INFO = "MN_DEFEND_ROLE_INFO",

	-- 主线
	MN_MAINLINE_CLICK_COPY = "MN_MAINLINE_CLICK_COPY",
	MN_MAINLINE_CLICK_SECTION_ITEM = "MN_MAINLINE_CLICK_SECTION_ITEM",
	MN_MAINLINE_SECTION_BOX = "MN_MAINLINE_SECTION_BOX",
	MN_MAINLINE_BUY_TIMES = "MN_MAINLINE_BUY_TIMES",
	MN_MAINLINE_SET_DETAIL_ACTIVE = "MN_MAINLINE_SET_DETAIL_ACTIVE",
	MN_MAINLINE_COPY_ENTER_FAIL = "MN_MAINLINE_COPY_ENTER_FAIL",
	MN_MAINLINE_UPDATE_PANEL = "MN_MAINLINE_UPDATE_PANEL",
	MN_MAINLINE_XIANYUAN_RED_POINT = "MN_MAINLINE_XIANYUAN_RED_POINT",

	--坐骑
	MN_WUJIANG_RSP_EQUIP_HORSE = "MN_WUJIANG_RSP_EQUIP_HORSE",
	MN_WUJIANG_RSP_HORSE_IMPROVE_STAGE = "MN_WUJIANG_RSP_HORSE_IMPROVE_STAGE",
	MN_HUNT_RSP_HUNT_PANEL = "MN_HUNT_RSP_HUNT_PANEL",
	MN_HUNT_RSP_MAINTAIN = "MN_HUNT_RSP_MAINTAIN",
	MN_HUNT_RSP_LEVELUP = "MN_HUNT_RSP_LEVELUP",
	MN_HUNT_RSP_CLEAR_LEVELUP_CD = "MN_HUNT_RSP_CLEAR_LEVELUP_CD",
	MN_HUNT_RSP_HORSE_SHOW_PANEL = "MN_HUNT_RSP_HORSE_SHOW_PANEL",
	MN_HUNT_RSP_CLEAR_SHOW_CD = "MN_HUNT_RSP_CLEAR_SHOW_CD",
	MN_HUNT_RSP_GROUND_FIRST_ATTR = "MN_HUNT_RSP_GROUND_FIRST_ATTR",
	MN_HUNT_RSP_ACTIVE_ATTR = "MN_HUNT_RSP_ACTIVE_ATTR",
	MN_HUNT_RSP_FIRST_ATTR_DETAIL = "MN_HUNT_RSP_FIRST_ATTR_DETAIL",
	MN_HUNT_RSP_HORSE_SHOW = "MN_HUNT_RSP_HORSE_SHOW",
	MN_HUNT_RSP_SELECT_HORSE = "MN_HUNT_RSP_SELECT_HORSE",

	-- 神兵副本
	MN_SBCOPY_INFO_CHG = "MN_SBCOPY_INFO_CHG",
	MN_SBCOPY_TIMES_CHG = "MN_SBCOPY_TIMES_CHG",
	MN_SBCOPY_CLICK_COPY = "MN_SBCOPY_CLICK_COPY",

	--神兵
	MN_WUJIANG_RSP_EQUIP_SHENBING = "MN_WUJIANG_RSP_EQUIP_SHENBING",
	MN_WUJIANG_RSP_UNEQUIP_SHENBING = "MN_WUJIANG_RSP_UNEQUIP_SHENBING",
	MN_WUJIANG_RSP_SHENBING_IMPROVE_STAGE = "MN_WUJIANG_RSP_SHENBING_IMPROVE_STAGE",
	MN_WUJIANG_RSP_SHENBING_REBUILD = "MN_WUJIANG_RSP_SHENBING_REBUILD",
	MN_WUJIANG_RSP_CONFIRM_SHENBING_REBUILD = "MN_WUJIANG_RSP_CONFIRM_SHENBING_REBUILD",
	MN_WUJIANG_NTF_SHENBING_RED_POINT = "MN_WUJIANG_NTF_SHENBING_RED_POINT",

	--物品相关
	MN_BAG_ITEM_CHG = "MN_BAG_ITEM_CHG",
	MN_MOUNT_ITEM_CHG = "MN_MOUNT_ITEM_CHG",
	MN_SHENBING_ITEM_CHG = "MN_SHENBING_ITEM_CHG",
	MN_ITEM_LOCK_CHG = "MN_ITEM_LOCK_CHG",

	--竞技场相关
	MN_ARENA_UPDATE_PANEL = "MN_ARENA_UPDATE_PANEL",	--更新竞技场界面
	MN_ARENA_REFRESH_RIVAL = "MN_ARENA_REFRESH_RIVAL",	--更新竞技场对手列表
	MN_ARENA_UPDATE_ALL_RANK_INFO_LIST = "MN_ARENA_UPDATE_ALL_RANK_INFO_LIST",	--更新竞技场排行榜
	MN_ARENA_UPDATE_BATTLE_RECORD = "MN_ARENA_UPDATE_BATTLE_RECORD",		--更新竞技场战报界面
	MN_ARENA_UPDATE_DEFEND_LINEUP = "MN_ARENA_UPDATE_DEFEND_LINEUP",		--更新竞技场防守阵容
	MN_ARENA_UPDATE_CURRENT_RANKDAN = "MN_ARENA_UPDATE_CURRENT_RANKDAN",	--更新竞技场当前段位显示

	-- Boss
	MN_BOSS_RSP_ENHANCEATK = "MN_BOSS_RSP_ENHANCEATK",
	MN_BOSS_RSP_BUYFIGHTBOSS_TIME = "MN_BOSS_RSP_BUYFIGHTBOSS_TIME",
	MN_BOSS_RSP_WORLDBOSS_RANK = "MN_BOSS_RSP_WORLDBOSS_RANK",
	MN_BOSS_RSP_WORLDBOSS_RANK_YESTERDAY = "MN_BOSS_RSP_WORLDBOSS_RANK_YESTERDAY",
	MN_GUILDBOSS_RSP_BOSSINFO = "MN_GUILDBOSS_RSP_BOSSINFO",
	MN_GUILDBOSS_RSP_BOSSRANKINFO = "MN_GUILDBOSS_RSP_BOSSRANKINFO",
	MN_GUILDBOSS_BUYBUFF = "MN_GUILDBOSS_BUYBUFF",
	MN_GUILDBOSS_RESETBOSS = "MN_GUILDBOSS_RESETBOSS",
	MN_BOSS_RSP_WORLDBOSSINFO = "MN_BOSS_RSP_WORLDBOSSINFO",

	--主公
	MN_USER_RSP_CHANGENAME = "MN_USER_RSP_CHANGENAME",
	MN_USER_NTF_USER_INFO_CHG = "MN_USER_NTF_USER_INFO_CHG",
	MN_USER_RSP_BUY_STAMINA = "MN_USER_RSP_BUY_STAMINA",
	MN_USER_RSP_USE_HEAD_ICON = "MN_USER_RSP_USE_HEAD_ICON",
	MN_RANDOM_NAME = "MN_RANDOM_NAME",
	MN_USER_CREATE_ROLE = "MN_USER_CREATE_ROLE",
	MN_USER_DETAIL = "MN_USER_DETAIL", 
	MN_USER_SERVER_NOTICE = "MN_USER_SERVER_NOTICE",
	MN_USER_SERVER_NOTICE_POS = "MN_USER_SERVER_NOTICE_POS",
	MN_EXP_CHG = "MN_EXP_CHG",

	--星盘
	MN_STAR_PANEL_UPDATE = "MN_STAR_PANEL_UPDATE",		--更新星盘界面
	MN_STAR_PANEL_ON_ACTIVE_STAR = "MN_STAR_PANEL_ON_ACTIVE_STAR",		--激活星光
	MN_NTF_STAR_CHG = "MN_NTF_STAR_CHG",
	MN_ASSITS_TASK_STAR_PANEL_ACTIVE = "MN_ASSITS_TASK_STAR_PANEL_ACTIVE",
	
	-- Email
	MN_MAIL_RSP_MAILLIST = "MN_MAIL_RSP_MAILLIST",
	MN_MAIL_RSP_MAILREAD = "MN_MAIL_RSP_MAILREAD",
	MN_MAIL_RSP_TAKEATTACH = "MN_MAIL_RSP_TAKEATTACH",
	MN_MAIL_RSP_TAKEATTACHLIST = "MN_MAIL_RSP_TAKEATTACHLIST",
	MN_MAIL_ITEM_ONSELECT = "MN_MAIL_ITEM_ONSELECT",
	MN_MAIL_DELETEEMEIL = "MN_MAIL_DELETEEMEIL",

	--角色数据
	MN_VIGOR_CHG = "MN_VIGOR_CHG",    --体力改变
	MN_GOLD_CHG = "MN_GOLD_CHG",	  --元宝改变
	MN_LEVEL_CHG = "MN_LEVEL_CHG",     --level改变
	MN_RSP_HEARTBEAT = "MN_RSP_HEARTBEAT", --时间心跳

	--好友
	MN_FRIEND_LIST = "MN_FRIEND_LIST",								--更新好友列表
	MN_FRIEND_RECOMMEND_LIST = "MN_FRIEND_RECOMMEND_LIST",			--更新好友推荐列表
	MN_FRIEND_RECENT_LIST = "MN_FRIEND_RECENT_LIST",				--更新最近联系列表
	MN_FRIEND_SEARCH_PLAYER = "MN_FRIEND_SEARCH_PLAYER",			--更新搜索结果
	MN_FRIEND_BLACK_LIST = "MN_FRIEND_BLACK_LIST",					--更新黑名单列表
	MN_FRIEND_SEND_REQUEST = "MN_FRIEND_SEND_REQUEST",				--成功发送申请
	MN_FRIEND_TAKE_STAMINA = "MN_FRIEND_TAKE_STAMINA",				--成功领取体力
	MN_FRIEND_SEND_STAMINA = "MN_FRIEND_SEND_STAMINA",				--成功赠送体力
	MN_FRIEND_DELETE_APPLY_LIST = "MN_FRIEND_DELETE_APPLY_LIST",	--申请列表删除某项
	MN_FRIEND_FRIEND_DATA_CHG = "MN_FRIEND_FRIEND_DATA_CHG",		--好友信息发生变化
	MN_FRIEND_BATTLE_HELP_DATA = "MN_FRIEND_BATTLE_HELP_DATA",		--好友助战数据
	MN_FRIEND_DELETE_ONE_FRIEND = "MN_FRIEND_DELETE_ONE_FRIEND",	--删除某个好友
	MN_FRIEND_NTF_DELETE = "MN_FRIEND_NTF_DELETE",				--被某个好友删除
	MN_FFRIEND_INVITATION_LIST = "MN_FFRIEND_INVITATION_LIST",	--协同任务邀请列表
	MN_FFRIEND_INVITATION_CHG = "MN_FFRIEND_INVITATION_CHG",	--协同任务邀请数据发生变化
	MN_FFRIEND_INVITATION_OPEN = "MN_FFRIEND_INVITATION_OPEN",	--协同任务邀请开关变化
	MN_RSP_FRIEND_TASK_PANEL_INFO = "MN_RSP_FRIEND_TASK_PANEL_INFO",	--	更新好友任务面板
	MN_FRIEND_EMPLOY_LIST = "MN_FRIEND_EMPLOY_LIST", --好友雇佣列表
	MN_FRIEND_REMOVE_FROM_BLACKLIST = "MN_FRIEND_REMOVE_FROM_BLACKLIST",	--从黑名单界面中移除黑名单
	MN_FRIEND_ASSIST_TASK_OPEM = "MN_FRIEND_ASSIST_TASK_OPEM",	--协同任务显示开启变化
	MN_RSP_FRIEND_RED_POINT_INFO = "MN_RSP_FRIEND_RED_POINT_INFO",   -- 好友红点

	--聊天
	MN_CHAT_SEND_PRIVATE_SPEAK = "MN_CHAT_SEND_PRIVATE_SPEAK",			--发送私聊成功
	MN_CHAT_RECEIVE_PRIVATE_SPEAK = "MN_CHAT_RECEIVE_PRIVATE_SPEAK",	--接收到私聊信息
	MN_CHAT_RECEIVE_SYSTEM_SPEAK = "MN_CHAT_RECEIVE_SYSTEM_SPEAK",		--接收到系统聊天
	MN_CHAT_RECEIVE_WORLD_SPEAK = "MN_CHAT_RECEIVE_WORLD_SPEAK",		--接收到世界聊天
	MN_CHAT_RECEIVE_GUILD_SPEAK = "MN_CHAT_RECEIVE_GUILD_SPEAK",		--接收到军团聊天
	MN_CHAT_PRIVATE_MSG_LIST = "MN_CHAT_PRIVATE_MSG_LIST",				--私聊信息列表
	MN_CHAT_SYSTEM_SPEAK_MSG_LIST = "MN_CHAT_SYSTEM_SPEAK_MSG_LIST",	--系统聊天信息列表
	MN_CHAT_WORLD_SPEAK_MSG_LIST = "MN_CHAT_WORLD_SPEAK_MSG_LIST",		--世界聊天信息列表
	MN_CHAT_GUILD_SPEAK_MSG_LIST = "MN_CHAT_GUILD_SPEAK_MSG_LIST",		--军团聊天信息列表
	MN_CHAT_MAIN_CHAT_LIST = "MN_CHAT_MAIN_CHAT_LIST",

	MN_TIPS_MESSAGE_CHG = "MN_TIPS_MESSAGE_CHG",

	MN_BATTLE_SETTLEMENT_OPEN = "MN_BATTLE_SETTLEMENT_OPEN",
	MN_BATTLE_RECORD_OPEN = "MN_BATTLE_RECORD_OPEN",

	MN_BATTLE_SHOW_SELECTOR_TARGET = "MN_BATTLE_SHOW_SELECTOR_TARGET", -- 大招单体头像

	--排行榜
	MN_COMMONRANK_INFO = "MN_COMMONRANK_INFO", 
	MN_COMMONRANK_REQ_BUZHEN = "MN_COMMONRANK_REQ_BUZHEN",

	-- 墓穴副本
	MN_GRAVE_COPY_INFO_CHG = "MN_GRAVE_COPY_INFO_CHG",
	MN_GRAVE_COPY_TIMES_CHG = "MN_GRAVE_COPY_TIMES_CHG",
	MN_GRAVE_COPY_CLICK_COPY = "MN_GRAVE_COPY_CLICK_COPY",

	-- 任務
	MN_NTF_TASK_CHG = "MN_NTF_TASK_CHG",
	MN_RSP_TAKE_TASK_AWARD = "MN_RSP_TAKE_TASK_AWARD",
	MN_NTF_TASK_PROGRESS_CHG = "MN_NTF_TASK_PROGRESS_CHG",
	MN_NTF_SEVENDAYS_TASK_PROGRESS_CHG = "MN_NTF_SEVENDAYS_TASK_PROGRESS_CHG",
	MN_NTF_SEVENDAYS_TASK_CHG = "MN_NTF_SEVENDAYS_TASK_CHG",
	MN_ONCLICK_GOTO_TASK_PANEL = "MN_ONCLICK_GOTO_TASK_PANEL",
	MN_NTF_FRIEND_TASK_CHG = "MN_NTF_FRIEND_TASK_CHG",
	MN_OPEN_ASSIST_TASK = "MN_OPEN_ASSIST_TASK",

	--征战
	MN_FIGHTWAR_INFO = "MN_FIGHTWAR_INFO",
	MN_FIGHTWAR_UPDATE_LEFT_TIME = "MN_FIGHTWAR_UPDATE_LEFT_TIME",

	--命签
	MN_INSCRIPTION_COPY_INFO = "MN_INSCRIPTION_COPY_INFO",
	MN_INSCRIPTION_COPY_CLICK_COPY = "MN_INSCRIPTION_COPY_CLICK_COPY",

	--辕门
	MN_YUANMEN_RSP_PANEL = "MN_YUANMEN_RSP_PANEL",
	MV_YUANMEN_NTF_ONE_YUANMEN_CHG = "MV_YUANMEN_NTF_ONE_YUANMEN_CHG",
	MN_YUANMEN_RSQ_REFRESH = "MN_YUANMEN_RSQ_REFRESH",
	MN_YUANMEN_REFRESH_CALLBACK = "MN_YUANMEN_REFRESH_CALLBACK",
	MN_YUANMEN_RSP_BOX_AWARD = "MN_YUANMEN_RSP_BOX_AWARD", 
	MN_YUANMEN_NTF_ASSIST_TASK = "MN_YUANMEN_NTF_ASSIST_TASK",

	--点将
	MN_DIANJIANG_RSP_PANEL = "MN_DIANJIANG_RSP_PANEL",
	MN_DIANJIANG_ON_RECURIT = "MN_DIANJIANG_ON_RECURIT",
	MN_DIANJIANG_ON_GET_DAILY = "MN_DIANJIANG_ON_GET_DAILY",
	MN_DIANJIANG_ON_XIEJIA = "MN_DIANJIANG_ON_XIEJIA",
	MN_DIANJIANG_XINWU_CHG = "MN_DIANJIANG_XINWU_CHG",
	MN_DIANJIANG_TAKEN_TODAY_FULI = "MN_DIANJIANG_TAKEN_TODAY_FULI",
	MN_DIANJIANG_UPDATE_PRICE = "MN_DIANJIANG_UPDATE_PRICE",
	MN_DIANJIANG_XIEJIA_STATUS = "MN_DIANJIANG_XIEJIA_STATUS",

	--商店
	MN_SHOP_GET_PANEL_INFO = "MN_SHOP_GET_PANEL_INFO",
	MN_SHOP_CLICK_TAB_BTN = "MN_SHOP_CLICK_TAB_BTN",
	MN_VIP_SHOP_GET_PANEL_INFO = "MN_VIP_SHOP_GET_PANEL_INFO", 
	MN_SHOP_PRIVILEGE_RED_POINT = "MN_SHOP_PRIVILEGE_RED_POINT",

	MN_ERROR_CODE = "MN_ERROR_CODE",

	--神兽
	MN_GODBEAST_DATA_CHG = "MN_GODBEAST_DATA_CHG",
	MN_GODBEAST_SURE_FORGET_TALENT = "MN_GODBEAST_SURE_FORGET_TALENT",

	--神兽副本
	MN_RSP_DRAGON_COPY_INFO = "MN_RSP_DRAGON_COPY_INFO", 
	MN_DRAGONCOPY_RSP_FINISH_COPY = "MN_DRAGONCOPY_RSP_FINISH_COPY",
	MN_DRAGON_COPY_HARD_ITEM_CLICK = "MN_DRAGON_COPY_HARD_ITEM_CLICK",

	--武将胜点排行
	MN_WUJIANG_RSP_RANK = "MN_WUJIANG_RSP_RANK",
	MN_GODBEAST_SURE_FORGET_TALENT = "MN_GODBEAST_SURE_FORGET_TALENT",

	--军团争霸
	MN_GUILDWAR_PANEL_INFO = "MN_GUILDWAR_PANEL_INFO",
	MN_GUILDWAR_BASE_INFO = "MN_GUILDWAR_BASE_INFO",
	MN_GUILDWAR_ACHIEVEMENT_INFO = "MN_GUILDWAR_ACHIEVEMENT_INFO",
	MN_GUILDWAR_CITY_INFO = "MN_GUILDWAR_CITY_INFO",
	MN_GUILDWAR_GUILD_DETAIL = "MN_GUILDWAR_GUILD_DETAIL",
	MN_GUILDWAR_BUY_BUFF = "MN_GUILDWAR_BUY_BUFF",
	MN_GUILDWAR_HUSONG_INFO = "MN_GUILDWAR_HUSONG_INFO",
	MN_GUILDWAR_HUSONG_INVITE = "MN_GUILDWAR_HUSONG_INVITE",
	MN_GUILDWAR_HUSONG_MISSION_ACCEPT = "MN_GUILDWAR_HUSONG_MISSION_ACCEPT",
	--MN_GUILDWAR_DEF_BUZHEN_INFO = "MN_GUILDWAR_DEF_BUZHEN_INFO",
	MN_GUILDWAR_OFFENCE_CITY_BATTLE_END = "MN_GUILDWAR_OFFENCE_CITY_BATTLE_END",
	MN_GUILDWAR_OFFENCE_CITY_BATTLE_NEWS = "MN_GUILDWAR_OFFENCE_CITY_BATTLE_NEWS",

	MN_GUILDWAR_RSP_HUSONG_PANEL = "MN_GUILDWAR_RSP_HUSONG_PANEL",
	MN_GUILDWAR_RSP_HUSONG_PANEL_CUR_SEARCH_MISSION = "MN_GUILDWAR_RSP_HUSONG_PANEL_CUR_SEARCH_MISSION",
	MN_GUILDWAR_RSP_ACCEPT_MISSION = "MN_GUILDWAR_RSP_ACCEPT_MISSION", 
	MN_GUILDWAR_MISSION_FAIL = "MN_GUILDWAR_MISSION_FAIL",
	MN_GUILDWAR_MISSION_SUC = "MN_GUILDWAR_MISSION_SUC",
	MN_GUILDWAR_HUFA_INVITE = "MN_GUILDWAR_HUFA_INVITE",
	MN_GUILDWAR_RSP_TAKE_HUSONG_AWARD = "MN_GUILDWAR_RSP_TAKE_HUSONG_AWARD",



	--三国列传
	MN_LIEZHUAN_COUNTRY_INFO = "MN_LIEZHUAN_COUNTRY_INFO",
	MN_LIEZHUAN_UPDATE_TEAM = "MN_LIEZHUAN_UPDATE_TEAM",
	MN_LIEZHUAN_EXIT_TEAM = "MN_LIEZHUAN_EXIT_TEAM",
	MN_LIEZHUAN_TEAM_MEMBER_CHG = "MN_LIEZHUAN_TEAM_MEMBER_CHG",
	MN_LIEZHUAN_TEAM_STAT_TIME_CHG = "MN_LIEZHUAN_TEAM_STAT_TIME_CHG",
	MN_LIEZHUAN_INVITE_PANNEL_INFO = "MN_LIEZHUAN_INVITE_PANNEL_INFO",
	MN_LIEZHUAN_UPDATE_BUZHEN_INFO = "MN_LIEZHUAN_UPDATE_BUZHEN_INFO",
	MN_LIEZHUAN_UPDATE_READY_STATE = "MN_LIEZHUAN_UPDATE_READY_STATE",
	MN_LIEZHUAN_RSP_AUTO_FIGHT = "MN_LIEZHUAN_RSP_AUTO_FIGHT",
	MN_LIEZHUAN_INVITE_TEAM_INFO = "MN_LIEZHUAN_INVITE_TEAM_INFO",

	-- VIP
	MN_VIP_GIFT_TAKEN = "MN_VIP_GIFT_TAKEN",
	MN_VIP_CHG = "MN_VIP_CHG", 
	MN_RSP_SHOUCHONG_AWARD_INFO = "MN_RSP_SHOUCHONG_AWARD_INFO",
	MN_NTF_SHOUCHONG_AWARD_INFO = "MN_NTF_SHOUCHONG_AWARD_INFO",
	MN_RSP_SEVENDAYS_INFO = "MN_RSP_SEVENDAYS_INFO",
	MN_RSP_YUEKA_PANEL_INFO = "MN_RSP_YUEKA_PANEL_INFO",
	MN_NTF_YUEKA_PANEL_INFO = "MN_NTF_YUEKA_PANEL_INFO",
	MN_RSP_YUEKA_TAKE_AWARD = "MN_RSP_YUEKA_TAKE_AWARD",


	-- 引导
	MN_GUIDE_SET_EFFECT_ORDER = "MN_GUIDE_SET_EFFECT_ORDER",
	MN_GUIDE_RECOVER_EFFECT_ORDER = "MN_GUIDE_RECOVER_EFFECT_ORDER",

	MN_SHOU_CHONG_GET_AWARD = "MN_SHOU_CHONG_GET_AWARD",

	MN_RSP_SEVENDAYS_TASK_GET_AWARD = "MN_RSP_SEVENDAYS_TASK_GET_AWARD",
	MN_RSP_SEVENDAYS_TASK_BOX_AWARD = "MN_RSP_SEVENDAYS_TASK_BOX_AWARD",

	-- 登录
	MN_LOGIN_RELOGIN = "MN_LOGIN_RELOGIN",
	MN_LOGIN_SELECT_SERVER_GROUP = "MN_LOGIN_SELECT_SERVER_GROUP",
	MN_LOGIN_SELECT_SERVER = "MN_LOGIN_SELECT_SERVER",

	--赛马
	MN_HORSERACE_UPDATE_RANK = "MN_HORSERACE_UPDATE_RANK",
	MN_HORSERACE_COUNT_DOWN = "MN_HORSERACE_COUNT_DOWN",
	MN_HORSERACE_SHOW_CURRENT_RANK = "MN_HORSERACE_SHOW_CURRENT_RANK",
	MN_HORSERACE_SHOW_SELF_RANK = "MN_HORSERACE_SHOW_SELF_RANK",
	MN_HORSERACE_COMPLETE_BATTLE = "MN_HORSERACE_COMPLETE_BATTLE",
	MN_HORSERACE_PANNEL = "MN_HORSERACE_PANNEL",
	MN_HORSERACE_LEFTTIMES = "MN_HORSERACE_LEFTTIMES",

	-- 下载
	MN_DOWNLOAD_CANCLE = "MN_DOWNLOAD_CANCLE",
}

return UIMessageNames